import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Navbar from "../components/components-ui/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (  
    <div className="flex w-full h-screen px-3 py-2 bg-zinc-100 rounded-2xl">
      <div className="flex flex-col justify-around items-center gap-2.5 pb-4 w-40 min-h-full bg-zinc-950 rounded-2xl">
        <div className="text-center">
          <h1 className="text-2xl"><strong>PCE</strong>-<span className="text-lg">Tools</span></h1>
        </div>
        <div className="w-[50%] h-[70%]">
          <Navbar />
        </div>
      </div>
      <div className="w-full min-h-full p-4">
        {children}
      </div>
    </div>
  );
}
